import { expect, test } from "@playwright/test";

test.describe("Forecast cycle and exceptions", () => {
  test("runs a forecast cycle and shows it in the run history", async ({ page }) => {
    await page.goto("/forecast");
    await expect(page.getByRole("heading", { name: "Run Forecast Cycle" })).toBeVisible();

    await page.locator("#horizon").fill("3");
    await page.getByRole("button", { name: "Run Forecast Cycle" }).click();

    await expect(page.getByText(/Forecast complete/)).toBeVisible({ timeout: 20_000 });
    await expect(page.locator(".table tbody tr").first()).toBeVisible();
  });

  test("exceptions generated by the run appear on the exceptions page", async ({ page }) => {
    // The seeded dataset includes engineered spike/drop/stockout scenarios,
    // so a run must always produce at least one open exception.
    await page.goto("/forecast");
    await page.getByRole("button", { name: "Run Forecast Cycle" }).click();
    await expect(page.getByText(/Forecast complete/)).toBeVisible({ timeout: 20_000 });

    await page.goto("/exceptions");
    await expect(page.locator(".table tbody tr").first()).toBeVisible({ timeout: 15_000 });
  });

  test("acknowledging an exception updates its status", async ({ page }) => {
    await page.goto("/exceptions");
    await expect(page.locator(".table tbody tr").first()).toBeVisible({ timeout: 15_000 });

    const firstRow = page.locator(".table tbody tr").first();
    const ackButton = firstRow.getByRole("button", { name: "Ack" });
    if (await ackButton.isVisible()) {
      await ackButton.click();
      await expect(firstRow.getByText("Acknowledged")).toBeVisible({ timeout: 10_000 });
    }
  });

  test("filtering by severity narrows the exception list", async ({ page }) => {
    await page.goto("/exceptions");
    await expect(page.locator(".table tbody tr").first()).toBeVisible({ timeout: 15_000 });

    await page.getByRole("button", { name: "Critical" }).click();
    await expect(page.getByRole("button", { name: "Critical" })).toHaveClass(/active/);

    const rows = page.locator(".table tbody tr");
    const count = await rows.count();
    for (let i = 0; i < count; i++) {
      await expect(rows.nth(i).getByText("Critical")).toBeVisible();
    }
  });
});
