"""initial schema

Revision ID: 8a3f8765168a
Revises: 
Create Date: 2026-08-18 20:19:35.711497

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3f8765168a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_label', sa.String(length=128), nullable=False),
    sa.Column('requested_model', sa.String(length=32), nullable=False),
    sa.Column('horizon_periods', sa.Integer(), nullable=False),
    sa.Column('products_forecasted', sa.Integer(), nullable=False),
    sa.Column('products_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_region'), 'locations', ['region'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=16), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock_units', sa.Integer(), nullable=False),
    sa.Column('reorder_point_units', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('forecast_units', sa.Float(), nullable=False),
    sa.Column('lower_bound_units', sa.Float(), nullable=True),
    sa.Column('upper_bound_units', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('wape', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('model_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'product_id', 'period_start', name='uq_forecast_run_prod_period')
    )
    op.create_index('ix_forecast_product_period', 'forecasts', ['product_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_run_id'), 'forecasts', ['run_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=48), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_product_id'), 'insights', ['product_id'], unique=False)
    op.create_index(op.f('ix_insights_scope'), 'insights', ['scope'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('on_hand_units', sa.Integer(), nullable=False),
    sa.Column('on_order_units', sa.Integer(), nullable=False),
    sa.Column('allocated_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', 'snapshot_date', name='uq_inventory_product_loc_date')
    )
    op.create_index(op.f('ix_inventory_snapshots_location_id'), 'inventory_snapshots', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_snapshot_date'), 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_table('planning_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_for_period', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exception_product_type', 'planning_exceptions', ['product_id', 'exception_type'], unique=False)
    op.create_index('ix_exception_status_severity', 'planning_exceptions', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_planning_exceptions_exception_type'), 'planning_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_planning_exceptions_product_id'), 'planning_exceptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_planning_exceptions_status'), 'planning_exceptions', ['status'], unique=False)
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', 'period_start', name='uq_sales_product_location_period')
    )
    op.create_index(op.f('ix_sales_history_location_id'), 'sales_history', ['location_id'], unique=False)
    op.create_index(op.f('ix_sales_history_period_start'), 'sales_history', ['period_start'], unique=False)
    op.create_index(op.f('ix_sales_history_product_id'), 'sales_history', ['product_id'], unique=False)
    op.create_index('ix_sales_product_period', 'sales_history', ['product_id', 'period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_product_period', table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_product_id'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_period_start'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_location_id'), table_name='sales_history')
    op.drop_table('sales_history')
    op.drop_index(op.f('ix_planning_exceptions_status'), table_name='planning_exceptions')
    op.drop_index(op.f('ix_planning_exceptions_product_id'), table_name='planning_exceptions')
    op.drop_index(op.f('ix_planning_exceptions_exception_type'), table_name='planning_exceptions')
    op.drop_index('ix_exception_status_severity', table_name='planning_exceptions')
    op.drop_index('ix_exception_product_type', table_name='planning_exceptions')
    op.drop_table('planning_exceptions')
    op.drop_index(op.f('ix_inventory_snapshots_snapshot_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_location_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_insights_scope'), table_name='insights')
    op.drop_index(op.f('ix_insights_product_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_forecasts_run_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_index('ix_forecast_product_period', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_locations_region'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
