import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';

const product = {
  product_id: 'product-00001',
  sku: 'SKU-00001',
  product_name: 'Northstar Herbal Tea 34',
  category: 'Grocery',
  subcategory: 'Coffee & Tea',
  brand: 'Northstar',
  unit_cost: '8.56',
  unit_price: '13.00',
};

export function forecastPreviewResponse(horizonMonths = 6) {
  return {
    forecast_id: 'preview-test-0001',
    store_id: 'store-001',
    product,
    selected_model: 'SeasonalNaive',
    training_cutoff: '2025-12-01',
    horizon_months: horizonMonths,
    interval_level: 90,
    intermittent_demand: false,
    validation_origins: 2,
    selected_metrics: {
      wape: 0.206,
      mase: 1.01,
      rmse: 25.41,
      bias: 0.0801,
      interval_coverage: 0.917,
      validation_points: 12,
    },
    evaluations: [
      {
        model_name: 'Naive',
        status: 'succeeded',
        validation_origins: 2,
        metrics: {
          wape: 0.347,
          mase: 1.7,
          rmse: 42.24,
          bias: 0.045,
          interval_coverage: 1,
          validation_points: 12,
        },
        failure_detail: null,
      },
      {
        model_name: 'SeasonalNaive',
        status: 'succeeded',
        validation_origins: 2,
        metrics: {
          wape: 0.206,
          mase: 1.01,
          rmse: 25.41,
          bias: 0.0801,
          interval_coverage: 0.917,
          validation_points: 12,
        },
        failure_detail: null,
      },
    ],
    forecasts: Array.from({ length: horizonMonths }, (_, index) => ({
      period_start: `2026-${String(index + 1).padStart(2, '0')}-01`,
      forecast_value: 120 - index * 4,
      lower_bound: 80 - index * 2,
      upper_bound: 160 - index * 2,
      horizon: index + 1,
    })),
  };
}

export function demandSignalsResponse() {
  return [
    {
      signal_id: 'signal-trend-1',
      store_id: 'store-001',
      product_id: 'product-00001',
      sku: 'SKU-00001',
      signal_type: 'trend',
      direction: 'growing',
      severity: 'watch',
      period_start: '2025-12-01',
      title: 'Demand is growing',
      description: 'Recent demand is materially above the prior year.',
      metric_name: 'recent_vs_prior_year_change',
      metric_value: 0.184,
      baseline_value: 124.2,
      threshold_value: 0.1,
      evidence: {
        recent_12_month_average: 147.1,
        prior_12_month_average: 124.2,
        absolute_change_units: 22.9,
        percent_change: 0.184,
        robust_monthly_slope: 1.4,
        relative_monthly_slope: 0.01,
      },
    },
    {
      signal_id: 'signal-seasonal-1',
      store_id: 'store-001',
      product_id: 'product-00001',
      sku: 'SKU-00001',
      signal_type: 'seasonality',
      direction: 'seasonal',
      severity: 'info',
      period_start: '2025-12-01',
      title: 'Annual seasonality detected',
      description: 'Demand has a strong relationship with the same months in prior years.',
      metric_name: 'lag_12_correlation',
      metric_value: 0.82,
      baseline_value: null,
      threshold_value: 0.6,
      evidence: { lag_months: 12, correlation: 0.82, paired_observations: 48 },
    },
    {
      signal_id: 'signal-spike-1',
      store_id: 'store-001',
      product_id: 'product-00001',
      sku: 'SKU-00001',
      signal_type: 'anomaly',
      direction: 'spike',
      severity: 'warning',
      period_start: '2025-10-01',
      title: 'Demand spike detected',
      description: 'Demand was above its trailing 12-month baseline by a material amount.',
      metric_name: 'robust_anomaly_score',
      metric_value: 5.7,
      baseline_value: 128,
      threshold_value: 3.5,
      evidence: {
        observed_demand: 210,
        trailing_12_month_median: 128,
        deviation_units: 82,
        robust_anomaly_score: 5.7,
        minimum_absolute_change_units: 32,
      },
    },
  ];
}

export function planningExceptionsResponse() {
  const common = {
    store_id: 'store-001',
    product_id: 'product-00001',
    sku: 'SKU-00001',
    status: 'open',
    created_at: '2026-01-15T12:00:00Z',
  };
  return [
    {
      ...common,
      exception_id: 'exception-stockout-1',
      exception_type: 'potential_stockout',
      severity: 'critical',
      priority_score: 100,
      relevant_period: '2026-01-29',
      title: 'Potential stockout before replenishment',
      description: 'Projected inventory falls below zero before replenishment arrives.',
      metric_name: 'projected_inventory_units',
      metric_value: -51.13,
      threshold_value: 0,
      evidence: {
        available_inventory: 12,
        on_order_due_within_lead_time: 0,
        forecast_demand_during_lead_time: 63.13,
        projected_inventory: -51.13,
        safety_stock: 31,
        selected_model: 'AutoETS',
      },
      related_signal_id: null,
      related_risk_id: 'risk-test-1',
      related_forecast_id: 'preview-risk-1',
    },
    {
      ...common,
      exception_id: 'exception-spike-1',
      exception_type: 'demand_spike',
      severity: 'high',
      priority_score: 80,
      relevant_period: '2025-10-01',
      title: 'Review unusual demand spike',
      description: 'Observed demand materially exceeded its recent baseline.',
      metric_name: 'robust_anomaly_score',
      metric_value: 5.7,
      threshold_value: 3.5,
      evidence: { observed_demand: 210, trailing_12_month_median: 128 },
      related_signal_id: 'signal-spike-1',
      related_risk_id: null,
      related_forecast_id: null,
    },
    {
      ...common,
      exception_id: 'exception-bias-1',
      exception_type: 'forecast_bias',
      severity: 'medium',
      priority_score: 52,
      relevant_period: '2025-12-01',
      title: 'Significant forecast bias',
      description: 'Backtesting shows systematic under-forecasting.',
      metric_name: 'forecast_bias',
      metric_value: -0.18,
      threshold_value: 0.15,
      evidence: { bias: -0.18, wape: 0.21, validation_points: 24, selected_model: 'AutoETS' },
      related_signal_id: null,
      related_risk_id: null,
      related_forecast_id: 'preview-six-month-1',
    },
  ];
}

const forecastRun = {
  run_id: 'forecast-test-run-1',
  data_version: 'test-v1',
  status: 'completed',
  created_at: '2026-01-15T12:00:00Z',
  training_cutoff: '2025-12-01',
  horizon_months: 6,
  interval_level: 90,
  series_count: 120,
  successful_series_count: 119,
  failed_series_count: 1,
  evaluation_count: 570,
  forecast_count: 714,
};

function portfolioOverviewResponse(storeId: string | null) {
  const storeName = storeId ? 'Toronto Central' : 'All stores';
  return {
    run_id: forecastRun.run_id,
    data_version: 'test-v1',
    training_cutoff: '2025-12-01',
    horizon_months: 6,
    store_id: storeId,
    store_name: storeName,
    series_count: storeId ? 24 : 120,
    recent_12_month_demand: storeId ? 14220 : 70991,
    prior_12_month_demand: storeId ? 13800 : 70268,
    demand_change: storeId ? 0.0304 : 0.0103,
    forecast_horizon_demand: storeId ? 7280 : 36367,
    median_series_wape: 0.217,
    median_series_mase: 0.881,
    median_absolute_bias: 0.0495,
    weighted_interval_coverage: 0.883,
    risk_counts: {
      stockout: storeId ? 8 : 42,
      below_safety_stock: storeId ? 4 : 20,
      healthy: storeId ? 9 : 42,
      excess: storeId ? 3 : 16,
      unavailable: 0,
    },
    timeline: Array.from({ length: 30 }, (_, index) => {
      const date = new Date(Date.UTC(2024, index, 1));
      const periodStart = date.toISOString().slice(0, 10);
      return {
        period_start: periodStart,
        actual_units: index < 24 ? 5600 + index * 19 : null,
        forecast_units: index >= 24 ? 6000 - (index - 24) * 35 : null,
      };
    }),
    priority_exceptions: [
      {
        exception_id: 'overview-stockout-1',
        store_id: 'store-004',
        store_name: 'Calgary West',
        product_id: 'product-00007',
        sku: 'SKU-00007',
        product_name: 'Field & Mill Granola 93',
        category: 'Grocery',
        exception_type: 'potential_stockout',
        severity: 'critical',
        priority_score: 100,
        title: 'Potential stockout before replenishment',
        description: 'Projected inventory falls below zero before replenishment arrives.',
        metric_name: 'projected_inventory_units',
        metric_value: -46.45,
        threshold_value: 0,
        selected_model: 'AutoTheta',
      },
      {
        exception_id: 'overview-bias-1',
        store_id: 'store-001',
        store_name: 'Toronto Central',
        product_id: 'product-00002',
        sku: 'SKU-00002',
        product_name: 'Harbor Sparkling Water 12',
        category: 'Beverages',
        exception_type: 'forecast_bias',
        severity: 'medium',
        priority_score: 52,
        title: 'Significant forecast bias',
        description: 'Rolling-origin validation shows systematic forecasting bias.',
        metric_name: 'forecast_bias',
        metric_value: -0.18,
        threshold_value: 0.15,
        selected_model: 'SeasonalNaive',
      },
    ],
  };
}

const forecastSeries = [
  {
    run_id: forecastRun.run_id,
    store_id: 'store-001',
    product_id: 'product-00001',
    sku: 'SKU-00001',
    product_name: 'Northstar Herbal Tea 34',
    category: 'Grocery',
    status: 'succeeded',
    selected_model: 'AutoETS',
    wape: 0.1726,
    mase: 0.839,
    rmse: 24.09,
    bias: 0.0896,
    interval_coverage: 0.875,
    validation_points: 24,
    failure_detail: null,
  },
  {
    run_id: forecastRun.run_id,
    store_id: 'store-001',
    product_id: 'product-00002',
    sku: 'SKU-00002',
    product_name: 'Harbor Sparkling Water 12',
    category: 'Beverages',
    status: 'succeeded',
    selected_model: 'SeasonalNaive',
    wape: 0.21,
    mase: 1.02,
    rmse: 19.2,
    bias: -0.04,
    interval_coverage: 0.917,
    validation_points: 24,
    failure_detail: null,
  },
];

export const server = setupServer(
  http.get('*/api/v1/stores', () =>
    HttpResponse.json([
      {
        store_id: 'store-001',
        store_code: 'TOR-01',
        store_name: 'Toronto Central',
        city: 'Toronto',
        region: 'Ontario',
        country: 'Canada',
        timezone: 'America/Toronto',
      },
    ]),
  ),
  http.get('*/api/v1/products', () => HttpResponse.json([product])),
  http.get('*/api/v1/demand/series', () =>
    HttpResponse.json({
      store_id: 'store-001',
      product,
      policy: {
        lead_time_days: 14,
        safety_stock: 31,
        reorder_point: 81,
        minimum_order_quantity: 30,
        order_multiple: 10,
        service_level_target: 0.97,
      },
      observations: [
        { period_start: '2024-01-01', demand_units: 149 },
        { period_start: '2024-02-01', demand_units: 163 },
      ],
      summary: {
        period_start: '2024-01-01',
        period_end: '2024-02-01',
        total_units: 312,
        average_monthly_units: 156,
        minimum_monthly_units: 149,
        maximum_monthly_units: 163,
        zero_demand_months: 0,
      },
    }),
  ),
  http.get('*/api/v1/signals', () => HttpResponse.json(demandSignalsResponse())),
  http.get('*/api/v1/inventory/positions', () =>
    HttpResponse.json({
      store_id: 'store-001',
      product_id: 'product-00001',
      sku: 'SKU-00001',
      snapshot_at: '2026-01-15T12:00:00Z',
      on_hand: 80,
      allocated: 20,
      on_order: 40,
      on_order_due_within_lead_time: 10,
      next_expected_receipt_at: '2026-01-22T12:00:00Z',
      lead_time_days: 14,
      safety_stock: 31,
    }),
  ),
  http.get('*/api/v1/inventory/risks', () =>
    HttpResponse.json({
      risk_id: 'risk-test-0001',
      store_id: 'store-001',
      product_id: 'product-00001',
      sku: 'SKU-00001',
      classification: 'below_safety_stock',
      severity: 'watch',
      snapshot_at: '2026-01-15T12:00:00Z',
      replenishment_arrival_at: '2026-01-29T12:00:00Z',
      available_inventory: 60,
      on_order_due_within_lead_time: 10,
      forecast_demand_during_lead_time: 55,
      projected_inventory: 15,
      safety_stock: 31,
      coverage_months: 0.13,
      excess_coverage_threshold_months: 6,
      selected_model: 'SeasonalNaive',
      forecast_id: 'preview-risk-test',
      training_cutoff: '2025-12-01',
      forecast_horizon_months: 1,
    }),
  ),
  http.get('*/api/v1/exceptions', () => HttpResponse.json(planningExceptionsResponse())),
  http.get('*/api/v1/forecast-runs', () => HttpResponse.json([forecastRun])),
  http.get('*/api/v1/dashboard/summary', ({ request }) => {
    const storeId = new URL(request.url).searchParams.get('store_id');
    return HttpResponse.json(portfolioOverviewResponse(storeId));
  }),
  http.get('*/api/v1/forecast-runs/:runId/series', () => HttpResponse.json(forecastSeries)),
  http.get('*/api/v1/forecast-runs/:runId/evaluations', ({ request }) => {
    const productId = new URL(request.url).searchParams.get('product_id');
    const selectedModel = productId === 'product-00002' ? 'SeasonalNaive' : 'AutoETS';
    return HttpResponse.json([
      {
        run_id: forecastRun.run_id,
        store_id: 'store-001',
        product_id: productId,
        sku: productId === 'product-00002' ? 'SKU-00002' : 'SKU-00001',
        model_name: selectedModel,
        selected: true,
        status: 'succeeded',
        validation_origins: 4,
        wape: productId === 'product-00002' ? 0.21 : 0.1726,
        mase: 0.839,
        rmse: 24.09,
        bias: 0.0896,
        interval_coverage: 0.875,
        validation_points: 24,
        failure_detail: null,
      },
      {
        run_id: forecastRun.run_id,
        store_id: 'store-001',
        product_id: productId,
        sku: productId === 'product-00002' ? 'SKU-00002' : 'SKU-00001',
        model_name: 'Naive',
        selected: false,
        status: 'succeeded',
        validation_origins: 4,
        wape: 0.31,
        mase: 1.4,
        rmse: 35,
        bias: 0.12,
        interval_coverage: 0.75,
        validation_points: 24,
        failure_detail: null,
      },
    ]);
  }),
  http.get('*/api/v1/forecasts', ({ request }) => {
    const productId = new URL(request.url).searchParams.get('product_id');
    return HttpResponse.json(
      Array.from({ length: 6 }, (_, index) => ({
        run_id: forecastRun.run_id,
        store_id: 'store-001',
        product_id: productId,
        sku: productId === 'product-00002' ? 'SKU-00002' : 'SKU-00001',
        period_start: `2026-${String(index + 1).padStart(2, '0')}-01`,
        forecast_value: 120 - index * 3,
        lower_bound: 80 - index,
        upper_bound: 160 - index,
        horizon: index + 1,
        selected_model: productId === 'product-00002' ? 'SeasonalNaive' : 'AutoETS',
        training_cutoff: '2025-12-01',
      })),
    );
  }),
  http.post('*/api/v1/forecast-previews', async ({ request }) => {
    const payload = (await request.json()) as { horizon_months: number };
    return HttpResponse.json(forecastPreviewResponse(payload.horizon_months));
  }),
);
